### ISSUE TITLE
Generate proper search.json

### ISSUE THREAD

**Issue by amenk** [AddisMap/AddisMapTransit#1]
With the steps in our DEVELOPMENT.md 

```
docker run --volume /tmp:/data osm-search-data-export  --input overpass --bbox "8.82,38.63,9.11,38.91"   --output json --outpath /data/search.json
```

The search data cannot be loaded.

I tried adding

`{"_version":"3.1","_fields":{` around the JSON manually but it also does not work.

How to generate the proper search.json for Trufi core v3?

**Comment by GustavoTCh** [comment]
@amenk, You need to use the "search-compact.json" file generated by the command.

The left side is a compact file and the right side is a normal file
![Screen Shot 2022-09-18 at 08 26 28](https://user-images.githubusercontent.com/42806689/190902221-b2856e64-0ad8-45c8-9325-6f4e2c146b09.png)

**Comment by amenk** [comment]
@GustavoTCh works well, thank you very much

See also https://github.com/trufi-association/osm-search-data-export/pull/14
